### ISSUE TITLE
运行test.py、run_csl.py报错

### ISSUE THREAD

**Issue by zhenhao-huang** [renmada/t5-pegasus-pytorch#5]
修改`test.py`中的路径为`t5_pegasus_torch`模型路径运行，报如下错误：

Traceback (most recent call last):
  File "/home/klein/Desktop/summary/t5-pegasus-pytorch-main/test.py", line 41, in <module>
    name='T5',
  File "/home/klein/anaconda3/lib/python3.6/site-packages/bert4keras/models.py", line 2440, in build_transformer_model
    transformer = MODEL(**configs)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/bert4keras/models.py", line 2326, in __init__
    super(T5, self).__init__(**kwargs)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/bert4keras/snippets.py", line 679, in new_func
    return func(self, *args, **kwargs)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/bert4keras/models.py", line 1751, in __init__
    super(T5_Base, self).__init__(**kwargs)
TypeError: __init__() missing 5 required positional arguments: 'hidden_size', 'num_hidden_layers', 'num_attention_heads', 'intermediate_size', and 'hidden_act'

`run_csl.py`显示缺少`bert4torch`这个库，请问有这个库吗

**Comment by renmada** [comment]
test.py好像是你的bert4keras的版本问题，建议试试最新的版本。
run_csl.py，你把第一行注释掉试试

**Comment by zhenhao-huang** [comment]
@renmada 
1.是最新的`0.10.5`，`0.9.1`以上版本`bert4keras`都不行，`transformers`也是最新的
2.注释掉，显示缺少`PermissionError: [Errno 13] Permission denied: '/root/csl/train.tsv'`
