### ISSUE TITLE
你好作者，我的代码提示此错误ValueError: You have to specify either input_ids or inputs_embeds，能提示一下吗

### ISSUE THREAD

**Issue by wangyudong1997** [renmada/t5-pegasus-pytorch#76]
Validation sanity check: 0it [00:00, ?it/s]/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:105: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Validation sanity check:   0%|                                                                                                                 | 0/1 [00:00<?, ?it/s]/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:3619: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(
Traceback (most recent call last):
  File "/home/wyd21/t5-pegasus-pytorch-main/train.py", line 29, in <module>
    trainer.fit(model, train_data, dev_data)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1122, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 158, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 392, in validation_step
    return self.model(*args, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/fairscale/nn/data_parallel/sharded_ddp.py", line 230, in forward
    return self.module(*inputs, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 93, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/home/wyd21/t5-pegasus-pytorch-main/models.py", line 113, in validation_step
    pred = self.predict_batch(batch)
  File "/home/wyd21/t5-pegasus-pytorch-main/models.py", line 96, in predict_batch
    pred = self.model.generate(**model_kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/transformers/generation/utils.py", line 1611, in generate
    return self.beam_search(
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/transformers/generation/utils.py", line 2909, in beam_search
    outputs = self(
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyd21/t5-pegasus-pytorch-main/models.py", line 1327, in forward
    outputs = super().forward(input_ids,
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 1683, in forward
    encoder_outputs = self.encoder(
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 983, in forward
    raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
ValueError: You have to specify either input_ids or inputs_embeds

**Comment by renmada** [comment]
你用的什么模型，t5-copy吗？

**Comment by wangyudong1997** [comment]
是的

**Comment by renmada** [comment]
可能是transfomers 版本的问题，试试5.11.0

**Comment by wangyudong1997** [comment]
ERROR: Ignored the following yanked versions: 4.14.0, 4.25.0
ERROR: Could not find a version that satisfies the requirement transformers==5.11.0 (from versions: 0.1, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.11.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.2.0, 3.3.0, 3.3.1, 3.4.0, 3.5.0, 3.5.1, 4.0.0rc1, 4.0.0, 4.0.1, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.3.0rc1, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.5.1, 4.6.0, 4.6.1, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.9.0, 4.9.1, 4.9.2, 4.10.0, 4.10.1, 4.10.2, 4.10.3, 4.11.0, 4.11.1, 4.11.2, 4.11.3, 4.12.0, 4.12.1, 4.12.2, 4.12.3, 4.12.4, 4.12.5, 4.13.0, 4.14.1, 4.15.0, 4.16.0, 4.16.1, 4.16.2, 4.17.0, 4.18.0, 4.19.0, 4.19.1, 4.19.2, 4.19.3, 4.19.4, 4.20.0, 4.20.1, 4.21.0, 4.21.1, 4.21.2, 4.21.3, 4.22.0, 4.22.1, 4.22.2, 4.23.0, 4.23.1, 4.24.0, 4.25.1, 4.26.0, 4.26.1, 4.27.0, 4.27.1, 4.27.2, 4.27.3, 4.27.4, 4.28.0, 4.28.1, 4.29.0, 4.29.1, 4.29.2, 4.30.0, 4.30.1, 4.30.2, 4.31.0, 4.32.0, 4.32.1, 4.33.0, 4.33.1, 4.33.2, 4.33.3, 4.34.0, 4.34.1, 4.35.0, 4.35.1, 4.35.2, 4.36.0)
我这显示最高版本4.36.0

**Comment by renmada** [comment]
不好意思，记错了4.11.0

**Comment by wangyudong1997** [comment]
File "/home/wyd21/t5-pegasus-pytorch-main/train.py", line 29, in <module>
    trainer.fit(model, train_data, dev_data)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1122, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 158, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 392, in validation_step
    return self.model(*args, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/fairscale/nn/data_parallel/sharded_ddp.py", line 230, in forward
    return self.module(*inputs, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 93, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/home/wyd21/t5-pegasus-pytorch-main/models.py", line 113, in validation_step
    pred = self.predict_batch(batch)
  File "/home/wyd21/t5-pegasus-pytorch-main/models.py", line 96, in predict_batch
    pred = self.model.generate(**model_kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/transformers/generation_utils.py", line 922, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(input_ids, model_kwargs)
  File "/home/wyd21/t5-pegasus-pytorch-main/models.py", line 1275, in _prepare_encoder_decoder_kwargs_for_generation
    model_input_name = model_input_name if model_input_name is not None else self.main_input_name
  File "/home/wyd21/miniconda3/envs/t5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'T5Copy' object has no attribute 'main_input_name'
不好意思，好像还是有问题

**Comment by wangyudong1997** [comment]
你好作者能提供一下您的包的版本吗，尝试了好多组合都失败了

**Comment by wang-TJ-20** [comment]
想问下你权重在哪下载的，我下载完后加载不上去tokenizer
