### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by ShiJiangYuan** [renmada/t5-pegasus-pytorch#77]
你好作者，我在运行t5-pegasus报错，请问是什么原因呢，具体报错如下：
Epoch 0:   0%|                                                                                                                                                                      | 0/397 [00:00<00:00, 1984.06it/s]Traceback (most recent call last):
  File "/data01/SuXD_Grp/ZhaoTX_99/workspaces/t5/train.py", line 29, in <module>
    trainer.fit(model, train_data, dev_data)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 147, in advance
    result = self._run_optimization(batch_idx, split_batch, opt_idx, optimizer)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 201, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 395, in _optimizer_step
    model_ref.optimizer_step(
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1616, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 206, in step
    self.__optimizer_step(closure=closure, profiler_name=profiler_name, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 128, in __optimizer_step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 296, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 303, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 226, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/fairscale/optim/oss.py", line 232, in step
    loss = self.optim.step(closure=closure, **kwargs)  # type: ignore
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/transformers/optimization.py", line 457, in step
    loss = closure()
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 235, in _training_step_and_backward_closure
    result = self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, hiddens)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 548, in training_step_and_backward
    self.backward(result, optimizer, opt_idx)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 589, in backward
    result.closure_loss = self.trainer.accelerator.backward(result.closure_loss, optimizer, *args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 276, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, optimizer, *args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 78, in backward
    model.backward(closure_loss, optimizer, *args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1479, in backward
    loss.backward(*args, **kwargs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data01/SuXD_Grp/ZhaoTX_99/miniconda3/envs/t5/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by renmada** [comment]
解决了吗

**Comment by lichengyang666** [comment]
如何解决
